# Generated by Django 4.2.1 on 2023-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('phone', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.CharField(max_length=100)),
            ],
        ),
    ]
