# Generated by Django 4.2.1 on 2023-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skills_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='value',
            field=models.IntegerField(max_length=2),
        ),
    ]
